apiVersion: v2
name: aws-load-balancer-controller
description: AWS Load Balancer Controller Helm chart for Kubernetes
version: 3.0.0
appVersion: v3.0.0
home: https://github.com/aws/eks-charts
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
annotations:
  io.giantswarm.application.audience: all
  io.giantswarm.application.managed: "true"
  io.giantswarm.application.team: phoenix
  io.giantswarm.application.upstream-chart-version: "v3.0.0"
  io.giantswarm.application.upstream-chart-url: https://github.com/aws/eks-charts/tree/master/stable/aws-load-balancer-controller
  io.giantswarm.application.restrictions.cluster-singleton: "true"
  io.giantswarm.application.restrictions.compatible-providers: "aws"
sources:
  - https://github.com/aws/eks-charts
maintainers:
  - name: kishorj
    url: https://github.com/kishorj
    email: kishorj@users.noreply.github.com
  - name: m00nf1sh
    url: https://github.com/m00nf1sh
    email: m00nf1sh@users.noreply.github.com
keywords:
  - eks
  - alb
  - load balancer
  - ingress
  - nlb
